### ISSUE TITLE
Working days / hours 

### ISSUE THREAD

**Issue by bapiens** [neuronetio/gantt-elastic#11]
First of all amazing work!

Have you tough about adding an configuration option for working days?
Or even better with working hours?
Most of the gantt chart tools lack of this features, which makes them more or less not so useful.

Keep the good work!

**Comment by neuronetio** [comment]
Thanks 👍 
Yes, I have plans to add working days, but working hours sounds great too.
I will think of it in upcoming versions.
Thanks for feedback!

**Comment by mdieudonne** [comment]
> add working days
would be a great addtion!

**Comment by neuronetio** [comment]
working days arrived at ver 0.7.10 !

**Comment by GuillaumeMauginOSF** [comment]
Hello,
again amazing work 👍  This is the best tool I found to have a full-perso calendar. You said 
> working days arrived at ver 0.7.10 !

How can we filter by working days ?
Thanks,

**Comment by neuronetio** [comment]
```js
/* ...other options... */
calendar: {
      workingDays: [1, 2, 3, 4, 5],
}
/* ... */
```

**Comment by GuillaumeMauginOSF** [comment]
Hello,
unfortunately I was not able to view this options or any other ones... I might be doing something wrong.

I use a Vue.js component with 
```
<template>
     <gantt-elastic :tasks="tasks" :options="options">
      <gantt-elastic-header slot="header"></gantt-elastic-header>
    </gantt-elastic>
</template>

<script>
import GanttElastic from 'gantt-elastic'
import Header from 'gantt-elastic-header'

onst options = {
  calendar: {
    workingDays: [1, 2, 3, 4, 5]
  },
  title: {
    label: 'Test',
    html: false
  },
```

**Comment by neuronetio** [comment]
That is weird, which version do you use?

**Comment by GuillaumeMauginOSF** [comment]
I tried to install back again and I have the following versions : 
```
"gantt-elastic": "^1.0.3",
"gantt-elastic-header": "^0.1.11",
```
What's weird is that options are considered **only** if I change _taskList_  for example if I change 1 _label_ it works but not for the attributes  _title_ and also _locale_ ...

Again many thanks for this tool. I'd love to be able to use the options for working days to share with my team.
