### ISSUE TITLE
Rendering issue for the calendar / progress part.

### ISSUE THREAD

**Issue by renaudham** [neuronetio/gantt-elastic#12]
Hi

I have updated to the latest version of Vue and GanttElastic

I have a specific rendering issue

The task list is shown
The calendar/progressBar is visibly empty, but all elements seems rendered but hidden, outside/below of the calendar/Progress zone.

When I select the rendered elements via Console or Vue Console (in browser)
They are located below the chart zone,  and not visible
`<CalendarRow key='1547593200000h4'>
<CalendarRow key='1547593200000h5'>
<Grid>
<DependencyLines>
<Milestone>
<ChartText>
<ProgressBar>`
etc...

then when I look at the detail it seems that some option are not ok, maybe the issue could be there maybe not..
see "(error during evaluation)"

`<ProgressBar>
props
task:Object
data
$route
computed
getLinePoints:"M 232.04812454244004 0 L 232.04812454244004 24"
getLineStyle:"(error during evaluation)"
getProgressWidth:"50%"
getSolidStyle:"(error during evaluation)"
injected
root:gantt-elastic
props
options:Object
locale:Object
Before/After:"Expand"
Display task list:"Task list"
Now:"Now"
Task list width:"Task list"
X-Scale:"Zoom-X"
Y-Scale:"Zoom-Y"
code:"en"
taskList:Object
tasks:Array[10]
0:Object
allChildren:Array[0]
children:Array[0]
collapsed:false
dependencyLines:Array[0]
dependentOn:Array[0]
duration:432000
durationMs:432000000
height:24
id:1
label:"Make some noise"
mouseOver:false
name:"Make some noise"
parent:Object
parentId:null
parents:Array[1]
progress:85
start:"2019-01-04 00:00:00"
startDate:Object
startTime:1546556400000
style:Object (empty)
tooltip:Object
type:"milestone"
user:"<a href="https://www.google.com/search?q=John+Doe" target="_blank" style="color:#0077c0;">John Doe</a>"
visible:true
width:580.3703113561
x:116.27406227122002
y:6
`

`<Calendar>
Inspect DOM
Open in editor
data
$route
days:Array[14]
hours:Array[84]
months:Array[1]
0:Object
computed
daysStyle:"(error during evaluation)"
getDays:Array[14]
getHours:Array[84]
getMonths:Array[1]
0:Object
getWidth:1628.3368704513157
getX:0.25
getY:0.25
hoursStyle:"(error during evaluation)"
monthsStyle:"(error during evaluation)"
injected
root:gantt-elastic
props
options:Object
locale:Object
Before/After:"Expand"
Display task list:"Task list"
Now:"Now"
Task list width:"Task list"
X-Scale:"Zoom-X"
Y-Scale:"Zoom-Y"
code:"en"
`

hoping you have an idea for this..
Thanks
Regards

**Comment by neuronetio** [comment]
Hi,
could you provide some screenshots?
In the meantime, try to set width of the container (gantt parent) to 100% and height to some value (might be 100% too) .
Thanks

**Comment by renaudham** [comment]
More infos..

Note that it's purely a CSS issue.

I succedd to force to view the chart calendar by adding some CSS
gantt-elastic__main-view-container 
float: left;
    width: calc(100% - 610px);

gantt-elastic__task-list-container
float: left;

then the chart appear visible
BUT in this case I cannot scroll it at all... the bottom scroller does nothing..
![image](https://user-images.githubusercontent.com/5046926/50911320-ed5fae80-142f-11e9-970f-542dd5e0f6d0.png)

**Comment by neuronetio** [comment]
I see in your code some settings that doesn't exists anymore.
Try settings, columns and task from [this example](https://github.com/neuronetio/gantt-elastic/blob/master/examples/vue.edit.html)
some options are evolving now so after update when something is not working properly take a look at examples folder `vue.edit.html`.

**Comment by neuronetio** [comment]
By the way, if you want to style some element you should pass css (as key:value pair) to `styles` option.
Initial style rules looks like [this](https://github.com/neuronetio/gantt-elastic/blob/master/src/style.js)
Every element in gantt-elastic has its own class starting with `gantt-elastic-`.
Just ignore this prefix and you can modify those class inside settings. 
It will be important later when gantt printing and image download feature will be added.

**Comment by renaudham** [comment]
Hi
Sorry, I applied all you new codes and latest version etc
the issue remain, as you can see the screenshot,
![image](https://user-images.githubusercontent.com/5046926/51025243-c8804e00-158b-11e9-8f99-89a554557490.png)


the gantt-elastic__task-list-container and gantt-elastic__main-view-container miss a float left
and the gantt-elastic__container miss a width

when I set a width to gantt-gantt-elastic__container
and add 2 float left, to gantt-elastic__task-list-container  and gantt-elastic__main-view-container
it appear visually ok except that I cannot scroll left right the chart..

I tried a lot of combinations, like removing the gantt-elastic__svg-container > max-width: calc(100% - 17px);
==> same result, the chart appears with no way to scroll horizontally, but worse as I lose the vertical scrollbar

sorry for my specific case, any idea?

Note: I intend to put this in a future commercial product and therefore if I can sell it, give back a small % of the sales to you, when I would sell a version with gantt...
Still far from concrete currenlty and in tech prototype only.. 
my email: renaud@b-o-d.fr

thanks

**Comment by neuronetio** [comment]
For those who will come with the same problem:
problem was in @renaudham vue app - styles from gantt was not attached to head for some reason.
