### ISSUE TITLE
error while disabling Hour

### ISSUE THREAD

**Issue by mdieudonne** [neuronetio/gantt-elastic#13]
Hi, thanks for the great job.
This is the first time I open an issue. I'll just get to the point:

I keep having an error when I try to disable 'hour' in the Calendar options:
ReferenceError: "userOptions is not defined"

`calendar: {
      gap: 6,
      height: 0,
      hour: {
        height: 20,
        display: false,
        format: {
          long (date) {
            return dayjs(date)
              .locale(userOptions.locale.code)
              .format("HH:mm");
          },
          medium (date) {
            return dayjs(date)
              .locale(userOptions.locale.code)
              .format("HH:mm");
          },
          short (date) {
            return dayjs(date)
              .locale(userOptions.locale.code)
              .format("HH");
          }
        }
      },
      day: {
        height: 20,
        display: true,
        format: {
          long (date) {
            return dayjs(date)
              .locale(userOptions.locale.code)
              .format("DD dddd");
          },
          medium (date) {
            return dayjs(date)
              .locale(userOptions.locale.code)
              .format("DD ddd");
          },
          short (date) {
            return dayjs(date)
              .locale(userOptions.locale.code)
              .format("DD");
          }
        }
      },
      month: {
        height: 20,
        display: true,
        format: {
          short (date) {
            return dayjs(date)
              .locale(userOptions.locale.code)
              .format("MM");
          },
          medium (date) {
            return dayjs(date)
              .locale(userOptions.locale.code)
              .format("'YY MMM");
          },
          long (date) {
            return dayjs(date)
              .locale(userOptions.locale.code)
              .format("YYYY MMMM (MM)");
          }
        }
      }
    },`

**Comment by mdieudonne** [comment]
Shouldn't 'userOptions.locale.code' be 'options.locale.code' ?
no more error thrown, but not the expected behavior: see as below.

display: True:
![image](https://user-images.githubusercontent.com/32196785/51126914-91789980-1824-11e9-89e7-3fc1a4da98e4.png)

display: False:
![image](https://user-images.githubusercontent.com/32196785/51126829-64c48200-1824-11e9-8746-b62327bf94da.png)

**Comment by mdieudonne** [comment]
Is that me or display hours: false isn't working as expected in the last version 0.9.1?

![image](https://user-images.githubusercontent.com/32196785/52912331-497be500-32b0-11e9-8c23-3e8f2e0b009b.png)

Thx

**Comment by neuronetio** [comment]
I will check it later, code of calendar rows height has changed so most probably its gantt fault👎

**Comment by neuronetio** [comment]
fixed in 0.9.2
