### ISSUE TITLE
Add week number

### ISSUE THREAD

**Issue by mdieudonne** [neuronetio/gantt-elastic#14]
Another great option in addition of working days,
would be the Week Numbers.

Rgds,
Michael

**Comment by neuronetio** [comment]
But where to display those?
and how? :)

**Comment by neuronetio** [comment]
I could add another row to calendar - but header can become too bloated.
4 rows may became too heavy
Another option is to replace days with week number, and then move days into hours row.
That will fill those empty space on maximal zoom
That will fill the gap : )
Yeah, it will happen
Thanks again!
That is very good idea
Thanks! : )

I'm adding this topic to my TODO list.

**Comment by neuronetio** [comment]
Topic is closed but you can respond if you have some thoughts here

**Comment by mdieudonne** [comment]
Yeah, I guess week numbers are more relevant than hours for projects management.
Happy to help!
Can't wait to try
