### ISSUE TITLE
State tasks is not updating

### ISSUE THREAD

**Issue by sandeepkumarmunige** [neuronetio/gantt-elastic#15]
I am using  Gantt elastic component as a child in my component where I am sending the value for props 'tasks'  which is a list of tasks objects received from API response using axios. 'tasks' is a computed property which gets value from vuex. While loading the component, 'tasks' of parent is with the inital value from vuex state and is passed to GanttElastic. I see in GanttElastic that 'tasks' prop is used to initialize state.tasks where state is the data object in GanttElastic. When my action in vuex mutates the prop 'tasks', value is mutated in 'tasks' prop of GanttElastic but is not updating state.tasks (state.tasks is used for computed prop visibleTasks to render chart. ) state.tasks is assigned from prop in setup() method which is called only in the created() of GanttElastic , but not computed everytime when 'tasks' prop is changed. setup() or initialize() might be the proper method which should also be called when tasks prop is updated to update state.tasks. Could you please check on this and provide us a way to use the mutated prop 'tasks'

**Comment by neuronetio** [comment]
yeah, I must repair this quickly
maybe in the next week i will look at this
thank for feedback anyway

**Comment by neuronetio** [comment]
should be fixed in 0.7.0
let me know if problem still exists, I will reopen this issue
thanks for report, and leave a star

**Comment by sandeepkumarmunige** [comment]
Thank you for the fix. its working :)
