### ISSUE TITLE
Locale options doesn't seem to work

### ISSUE THREAD

**Issue by sandeepkumarmunige** [neuronetio/gantt-elastic#20]
Locale options sent are as below but could not get them loaded Gantt elastic. 

`				locale: {
					code: "en",
					Now: "Now",
					"X-Scale": "Zoom-X",
					"Y-Scale": "Zoom-Y",
					"Task list width": "Task list",
					"Before/After": "Expand",
					"Display task list": "Task list"
				}
			}`

![image](https://user-images.githubusercontent.com/3057466/51979783-0d751180-24b4-11e9-95ff-801807e2cfd8.png)

**Comment by mdieudonne** [comment]
Hey,

Works nice on my side : 

            locale: {
                code: customLocale,
                'Now': 'Aujourd\'hui',
                'X-Scale': 'Zoom',
                'Y-Scale': 'Interligne',
                'Task list width': 'Liste',
                'Before/After': 'Période',
                'Display task list': 'Liste'
            },

![image](https://user-images.githubusercontent.com/32196785/51988055-0b0abb80-24a4-11e9-99dc-443406485c6b.png)

**Comment by neuronetio** [comment]
@sandeepkumarmunige take a look at [this example](https://github.com/neuronetio/gantt-elastic/blob/master/examples/vue.edit.html)
You need to have header with sliders and labels to se translations for it.

You can also translate calendar dates as follows:
```javascript
locale: {
  code:'fr',
  'Now': 'Aujourd\'hui',
  'X-Scale': 'Zoom',
  'Y-Scale': 'Interligne',
  'Task list width': 'Liste',
   'Before/After': 'Période',
   'Display task list': 'Liste',
  weekdays: 'Dimanche_Lundi_Mardi_Mercredi_Jeudi_Vendredi_Samedi'.split('_'),
  months: 'Janvier_Février_Mars_Avril_Mai_Juin_Juillet_Août_Septembre_Octobre_Novembre_Décembre'.split('_'),
  monthsShort: 'janv_févr_mars_avril_mai_juin_juil_août_sept_oct_nov_déc'.split('_'),
  relativeTime: {
    future: 'dans %s',
    past: 'il y a %s',
    s: 'quelques secondes',
    m: 'une minute',
    mm: '%d minutes',
    h: 'une heure',
    hh: '%d heures',
    d: 'un jour',
    dd: '%d jours',
    M: 'un mois',
    MM: '%d mois',
    y: 'un an',
    yy: '%d ans'
  },
  ordinal: (n) => {
    const o = n === 1 ? 'er' : ''
    return `${n}${o}`
  }
}
```
