### ISSUE TITLE
collapse rows on loading

### ISSUE THREAD

**Issue by mdieudonne** [neuronetio/gantt-elastic#21]
Hi,

When loading the page with tens of sub-tasks, the cpu usage is very high.
~70% on my config.
Would it possible to add the option to collapse all tasks by default?

Thx,
Michael

**Comment by neuronetio** [comment]
I'm afraid that this would not help.
Of course I will add this feature, but I think that problem with performance is elsewhere.
I will try to optimize code at the end of work, before final release.

**Comment by mdieudonne** [comment]
I experience lags when all rows are expanded,
when some are collapsed: no lag.

**Comment by neuronetio** [comment]
Aha, I will add `collapsed` option to `tasks` so you could collapse them by default.

PS If you add `collapsed` property to task right now it will have `collapsed` only icon 😜

**Comment by neuronetio** [comment]
check out  0.7.4 version
just set `collapsed` property on task to  `true`

**Comment by mdieudonne** [comment]
Hey, thank for updating!
I found one problem though: 
When a row has no children, no "+" is displayed which is normal (but still I note the mouse pointer changes).
![image](https://user-images.githubusercontent.com/32196785/52114983-c26f1180-260d-11e9-8cc5-4bf49becaa37.png)

However when setting collapsed to true, just a vertical bar is displayed which is unexpected
![image](https://user-images.githubusercontent.com/32196785/52115012-d0bd2d80-260d-11e9-90ec-bbd4d28cf896.png)

**Comment by neuronetio** [comment]
ok, I'll fix this

**Comment by neuronetio** [comment]
@mdieudonne those `[+]` should work now (0.7.7)
