### ISSUE TITLE
Customizable task model

### ISSUE THREAD

**Issue by lucafaggianelli** [neuronetio/gantt-elastic#28]
**Is your feature request related to a problem? Please describe.**
If you have a different task model, that is, different properties instead of `label`, `start`, etc. you must create a copy of the tasks with the correct properties.

**Describe the solution you'd like**
It should be an option like `const options = { labelProp: 'title', startProp: 'startDate' }`

**Describe alternatives you've considered**
I fetch the task list and create a copy with the needed properties

I can work on this feature if you find it useful and need help!

This Gantt component is wonderful! Thanks a lot!
Luca

**Comment by neuronetio** [comment]
good idea

**Comment by neuronetio** [comment]
https://github.com/neuronetio/gantt-elastic/wiki/Task-properties-mapping

**Comment by lucafaggianelli** [comment]
Great! I'll test it out soon, thanks!
