### ISSUE TITLE
Support end date property in tasks instead of duration

### ISSUE THREAD

**Issue by lucafaggianelli** [neuronetio/gantt-elastic#29]
**Is your feature request related to a problem? Please describe.**
Make possible to use `duration` as well as `end` property for task duration/gantt bar width

**Describe the solution you'd like**
Support a property of `Date` type that defines task end, if both `duration` and `end` are present, priority is on 1 of the 2

**Describe alternatives you've considered**
I have 2 props in my task `startDate` and `dueDate` and I have to loop all tasks to create `task.duration = (task.dueDate - task.startDate) / 1000`

**Comment by neuronetio** [comment]
landed in my todo list

**Comment by neuronetio** [comment]
`end` property landed in latest version - it is millisecond timestamp or ISO date-time string
