### ISSUE TITLE
row click in table

### ISSUE THREAD

**Issue by FeFelix** [neuronetio/gantt-elastic#30]
I would like to know how to click on the table row, same as the @chart-project-click (vue) method but clicking on the table. 
Help?

**Comment by neuronetio** [comment]
I will add those events in the next version, maybe till monday
thanks!

**Comment by neuronetio** [comment]
I've added a task list events in 0.9.4
You can read about it here https://github.com/neuronetio/gantt-elastic/wiki/Mouse-&-touch-events

**Comment by FeFelix** [comment]
Thx  so much, I'll see
