### ISSUE TITLE
"TypeError: this.$store is undefined"

### ISSUE THREAD

**Issue by mdieudonne** [neuronetio/gantt-elastic#34]
Hi,

I migrated from 0.9.6 to 0.10.15 and I've got this error: **this.$store is undefined**
I import gantt-elastic in my project using Webpack, my index.js is : 
![image](https://user-images.githubusercontent.com/32196785/54537767-611fb980-4993-11e9-9ede-436ed2978424.png)
My entry point in my template is :     {{ encore_entry_script_tags('gantt-planning') }}

**Comment by neuronetio** [comment]
You need to have vuex like in this example https://github.com/neuronetio/vue-gantt-elastic/blob/master/src/App.vue

**Comment by mdieudonne** [comment]
Here is how I manage the upgrade from 0.9.6 to 0.10.15:

```
//Add
import Vuex from 'vuex';
Vue.use(Vuex)
const store = new Vuex.Store({
    state: {
        tasks: tasks,
        options: options
    }
});

new Vue({
  el:'#app',
...
    store,
    data() {
        return {
            tasks: tasks,
            options: options
        };
    },
    computed: {
        tasks() {
            return this.$store.state.tasks;
        },
        options() {
            return this.$store.state.options;
        }
    }
})
```
--------
In const options = { }
 `value: task => dayjs(task.start).format("DD/MM/YYYY"),`
```
  calendar: {
                hour: {
                    display: true
                }
            },
```

**Comment by neuronetio** [comment]
![image](https://user-images.githubusercontent.com/25027696/54552944-7efc1700-49b1-11e9-9000-ab5033262d43.png)

**Comment by mdieudonne** [comment]
when I try standalone code, CDN, I got this console error :
![image](https://user-images.githubusercontent.com/32196785/54587063-41ce6e00-4a1f-11e9-9413-be89d50ab022.png)

when I try to import gantt-elastic as a asset and compile with webpack, no console error, but 
![Capture](https://user-images.githubusercontent.com/32196785/54587338-1ac46c00-4a20-11e9-881f-d4a10e3cc611.jpg)

**Comment by mdieudonne** [comment]
my feeback, with a php backend. 
time() is in seconds - I needed to multiple by 1000
in my case : 'start' =>$lastItem->getTimestamp()*1000,

**Comment by mdieudonne** [comment]
when I don't set locale property in option, gantt is in Polish
when I set to 'fr', it is in english..
Am I missing something? Thanks

**Comment by neuronetio** [comment]
you must add all translations by yourself https://github.com/neuronetio/gantt-elastic/wiki/Locale

**Comment by mdieudonne** [comment]
yeah I copy the whole block locale property, which includes the translations, in the Options object,
it is not translated.
When I put the 'fr' block I got the english,
and by default it is in polish (learnt couple of words today ;)

![image](https://user-images.githubusercontent.com/32196785/54638292-ffdb1180-4a8a-11e9-83bc-11faab77d530.png)

**Comment by neuronetio** [comment]
hehe, ok I will check this

**Comment by neuronetio** [comment]
try gantt-elastic v 0.10.17

**Comment by mdieudonne** [comment]
> you must add all translations by yourself https://github.com/neuronetio/gantt-elastic/wiki/Locale

Just find out that it is needed to add a property : 
               ` weekdaysShort: 'Dim_Lun_Mar_Mer_Jeu_Ven_Sam'.split('_'),`
for full French translation, as in the example
