### ISSUE TITLE
<DemoHeader> won't show

### ISSUE THREAD

**Issue by mdieudonne** [neuronetio/gantt-elastic#35]
`<DemoHeader>` with controls won't show.

Here is the [example given earlier](https://github.com/neuronetio/vue-gantt-elastic/blob/master/src/App.vue)
And the result I've got : missing controls
![image](https://user-images.githubusercontent.com/32196785/54607190-10b96200-4a4e-11e9-9c6c-35c1dd709aac.png)
I also note we lose the bakcground color after a certain lenght
![image](https://user-images.githubusercontent.com/32196785/54607322-5fff9280-4a4e-11e9-868c-a868f4288ee8.png)

**Comment by neuronetio** [comment]
do you have some errors in the console?

**Comment by neuronetio** [comment]
ok, I have the same issue

**Comment by neuronetio** [comment]
try latest vue-gantt-elastic example and gantt-elastic 0.10.16

**Comment by mdieudonne** [comment]
demo-header is working. great!
2 more things though

Dates seems to be staggered when zoom is too important
![image](https://user-images.githubusercontent.com/32196785/54639954-e1771500-4a8e-11e9-8b9e-05c06e57bc48.png)
normal should be : 
![image](https://user-images.githubusercontent.com/32196785/54640191-7712a480-4a8f-11e9-8fee-dae543d9b5cd.png)

I also notice a bunch of events : Update Task
and it cause javascript engine to freeze (got this firefox message ''script may be running slow, stop or wait'').

**Comment by mdieudonne** [comment]
the freeze occures on both ff & Chrome when I click + to expand a Parent which has a lot (36) Children, WITH the Vue Dev Tool opened!

**Comment by neuronetio** [comment]
ok

**Comment by neuronetio** [comment]
while I'm working on solution you can just turn off events recording for now - it should not freeze anymore
![image](https://user-images.githubusercontent.com/25027696/54642236-687abc00-4a94-11e9-9312-bbe54e565749.png)

**Comment by neuronetio** [comment]
problem with disappearing days fixed in 0.10.18

**Comment by neuronetio** [comment]
0.12.1 is no longer based on vuex, so it will no longer freeze the development tools
take a look at https://github.com/neuronetio/vue-gantt-elastic
