### ISSUE TITLE
export 'mergeDeepReactive' was not found in './GanttElastic.vue

### ISSUE THREAD

**Issue by justyy** [neuronetio/gantt-elastic#36]
hi~
i want to use gantt-elastic in my project, but when i follow your demo, my terminal show the warning. just like this
![image](https://user-images.githubusercontent.com/7438323/54756315-f4225300-4c22-11e9-81f4-8d27d1db8863.png)

how can i fixed it?  thanks

**Comment by neuronetio** [comment]
what tools do you use? vue cli? webpack? rollup?
Show some configuration, plugins etc

mergeDeepReactive is exported, I don't know why your bundler doesn't see it
![image](https://user-images.githubusercontent.com/25027696/54781314-385e2500-4c1c-11e9-8d8b-40c5335c71a0.png)

**Comment by justyy** [comment]
vue: 2.5.10
vue-loader: 13.5.0
webpack: 3.10.0

is it my tools version didn't support it ?

**Comment by neuronetio** [comment]
Paste configuration

**Comment by justyy** [comment]
you mean the package.json ? 
"dependencies": {
    "axios": "0.17.1",
    "clipboard": "^2.0.1",
    "echarts": "^4.2.0-rc.1",
    "element-ui": "2.3.4",
    "font-awesome": "^4.7.0",
    "heatmap.js": "^2.0.5",
    "js-cookie": "2.2.0",
    "konva": "^2.5.1",
    "lodash": "^4.17.11",
    "markdown-it": "^8.4.1",
    "markdown-it-anchor": "^5.0.2",
    "markdown-it-container": "^2.0.0",
    "mockjs": "^1.0.1-beta3",
    "moment": "^2.24.0",
    "normalize.css": "7.0.0",
    "nprogress": "0.2.0",
    "qrcodejs2": "^0.0.2",
    "qs": "^6.5.1",
    "quill-image-drop-module": "^1.0.3",
    "quill-image-resize-module": "^3.0.0",
    "style-loader": "^0.21.0",
    "three.js": "^0.77.1",
    "transliteration": "^1.6.2",
    "vue": "2.5.10",
    "vue-i18n": "7.6.0",
    "vue-image-crop-upload": "^2.2.3",
    "vue-quill-editor": "^3.0.6",
    "vue-router": "3.0.1",
    "vue-slider-component": "^2.8.8",
    "vuex": "3.0.1"
  },
  "devDependencies": {
    "autoprefixer": "7.2.3",
    "babel-core": "6.26.0",
    "babel-eslint": "8.0.3",
    "babel-helper-vue-jsx-merge-props": "2.0.3",
    "babel-loader": "7.1.2",
    "babel-plugin-syntax-jsx": "6.18.0",
    "babel-plugin-transform-runtime": "6.23.0",
    "babel-plugin-transform-vue-jsx": "3.5.0",
    "babel-preset-env": "1.6.1",
    "babel-preset-stage-2": "6.24.1",
    "chalk": "2.3.0",
    "cheerio": "^1.0.0-rc.2",
    "copy-webpack-plugin": "4.2.3",
    "cross-env": "^5.1.5",
    "css-loader": "^0.28.11",
    "eslint": "4.19.1",
    "eslint-friendly-formatter": "3.0.0",
    "eslint-loader": "1.9.0",
    "eslint-plugin-html": "4.0.1",
    "eventsource-polyfill": "0.9.6",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.5",
    "friendly-errors-webpack-plugin": "1.6.1",
    "gantt-elastic": "^0.10.18",
    "html-webpack-plugin": "2.30.1",
    "husky": "^1.1.2",
    "lint-staged": "^7.3.0",
    "node-notifier": "5.1.2",
    "node-sass": "^4.7.2",
    "optimize-css-assets-webpack-plugin": "3.2.0",
    "ora": "1.3.0",
    "portfinder": "1.0.13",
    "postcss-import": "11.0.0",
    "postcss-loader": "2.0.9",
    "rimraf": "2.6.2",
    "sass-loader": "^7.0.3",
    "semver": "5.4.1",
    "shelljs": "0.7.8",
    "svg-sprite-loader": "3.5.2",
    "uglifyjs-webpack-plugin": "1.1.3",
    "url-loader": "0.6.2",
    "vue-loader": "13.5.0",
    "vue-markdown-loader": "^2.4.1",
    "vue-style-loader": "3.0.3",
    "vue-switches": "^2.0.1",
    "vue-template-compiler": "2.5.10",
    "webpack": "3.10.0",
    "webpack-bundle-analyzer": "2.9.1",
    "webpack-dev-server": "2.9.7",
    "webpack-merge": "4.1.1"
  }
Is this useful?

**Comment by neuronetio** [comment]
Do you have a webpack configuration file? `webpack.config.js`
I think that maybe updating webpack to v4 would help.

**Comment by justyy** [comment]
thanks
