### ISSUE TITLE
[vuex] duplicate getter key: GanttElastic/options

### ISSUE THREAD

**Issue by taowu-kooboo** [neuronetio/gantt-elastic#39]
**Describe the bug**
![image](https://user-images.githubusercontent.com/41357618/55047310-43331280-507f-11e9-96c8-3ae5b10b757b.png)

**To Reproduce**
1. Go to the gantt chart page 
2. Switch to a new page
3. Go back to the gantt chart page

**Expected behavior**
This is a bug or could you please help me to resolve this error, thank you. I use vue-cli3

**Comment by neuronetio** [comment]
Yeah this is a bug, because gantt-elastic is trying to register vuex module that is already registered when create cycle hook i fired.
From the next version I removed vuex entirely because it is pain in the ass to work with it on arrays with structure like gantt-elastic have, so the problem will be resolved.

**Comment by neuronetio** [comment]
For quick workaround you can add `this.$store.unregisterModule('GanttElastic')` to `beforeDestroy` life cycle hook.

**Comment by taowu-kooboo** [comment]
I have add ```this.$store.unregisterModule('GanttElastic')``` to ```beforeDestroy``` life cycle hook, when i switch to a new page or go back to the gantt cahrt page, it throws new errors.
![image](https://user-images.githubusercontent.com/41357618/55203477-6cca7600-5206-11e9-8993-20a23f8d32e9.png)
Looking forward to your next version, thank you for your answer.

**Comment by neuronetio** [comment]
ok, maybe till monday I will publish something

**Comment by neuronetio** [comment]
Try 0.12.1 but first take a look at https://github.com/neuronetio/vue-gantt-elastic
