### ISSUE TITLE
How to use this awesome thing in Angular?

### ISSUE THREAD

**Issue by Vbboi24** [neuronetio/gantt-elastic#40]
Hello, Is there anyway i can use this thing in Angular 6 ?

**Comment by neuronetio** [comment]
I do not know angular, but maybe it will be something similar to https://medium.com/@swarnakishore/how-to-include-and-use-jquery-in-angular-cli-project-592e0fe63176

You can try using the standalone version of gantt-elastic

**Comment by neuronetio** [comment]
closing, but you can respond here

I'm thinking about angular and react wrapper for gantt, will see

**Comment by boisamazing** [comment]
Agree, please consider Angular version.
