### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by dimm0** [neuronetio/gantt-elastic#41]
Trying the latest version in webpack vue-cli application.

The diagram is rendering 7 px tall

<img width="420" alt="Screen Shot 2019-04-10 at 10 57 28 PM" src="https://user-images.githubusercontent.com/1425007/55934014-243a9180-5be4-11e9-83ab-342a73a1ff8e.png">

Those small dots are the diagram. Exclamation marks are normal size.

I tried the webpack project, but it has the older version and no scripts to build easily..

Also errors in console:

<img width="418" alt="Screen Shot 2019-04-10 at 11 00 33 PM" src="https://user-images.githubusercontent.com/1425007/55934110-75e31c00-5be4-11e9-9160-5ce631d581ba.png">

Please help!

**Comment by neuronetio** [comment]
try now https://github.com/neuronetio/gantt-elastic-webpack

**Comment by neuronetio** [comment]
paste few task here and options you are using

**Comment by dimm0** [comment]
Using your options and tasks

With the latest version slightly better.

<img width="808" alt="Screen Shot 2019-04-15 at 11 47 31 PM" src="https://user-images.githubusercontent.com/1425007/56187909-e91bd200-5fd8-11e9-9ee5-16252c79de28.png">

<img width="1280" alt="Screen Shot 2019-04-15 at 11 48 30 PM" src="https://user-images.githubusercontent.com/1425007/56187939-00f35600-5fd9-11e9-97b6-537e219fcffa.png">

**Comment by neuronetio** [comment]
naaahh, you must have something wrong
paste some code
https://github.com/neuronetio/gantt-elastic/blob/master/src/GanttElastic.vue#L516
https://github.com/neuronetio/gantt-elastic/blob/master/src/style.js#L347
you can also try to delete `node_modules/@cache` dir

**Comment by neuronetio** [comment]
I also found a bug in firefox that could lead to this error :) check out 0.13.3 and let me now it is fixed

**Comment by neuronetio** [comment]
try the latest version

**Comment by dimm0** [comment]
Working! Thanks! 🎉

**Comment by dimm0** [comment]
Oops.. Not quite

<img width="990" alt="Screen Shot 2019-04-16 at 6 17 21 PM" src="https://user-images.githubusercontent.com/1425007/56254033-f6d26580-6073-11e9-9ba2-958c242ad9a4.png">

**Comment by neuronetio** [comment]
multiply duration by 1000 - it was changed from seconds to milliseconds like start property
