### ISSUE TITLE
ReferenceError: Header is not defined using standalone, pure-JS mode

### ISSUE THREAD

**Issue by partofthething** [neuronetio/gantt-elastic#42]
**Describe the bug**
I copied the demo code from the Readme into a html file and opened it. It gives an error on the Console: 
```
ReferenceError: Header is not defined
```
Even if I comment the line that's coming from out (from options), then there are no errors but nothing shows up on the page. Just a blank page. 

**To Reproduce**
1. Copy readme's HTML to a html file
2. Open it in web browser
3. See error and/or blank screen

**Expected behavior**
I'd expect a demo similar to what's shown in the screenshots to appear. 

**Screenshots**
Just blank screen

**Desktop (please complete the following information):**
 - OS: Windows 7 64-bit
 - Browser Firefox 66.0.2, Chrome 73.0.3683.103

**Comment by neuronetio** [comment]
I've updated readme, try it now

**Comment by partofthething** [comment]
Totally works. Thanks!
