### ISSUE TITLE
Can not support vue-slider-component with v3.x

### ISSUE THREAD

**Issue by HavenLin** [neuronetio/gantt-elastic#43]
### **Is your feature request related to a problem? Please describe.**
I am trying to get started for gantt-elastic, when I ran vue project in local, I found it is compiler error that vue-slider-component v3.x does not have vue2-slider.vue. 

[this is git branch of vue-slider-component v2.x](https://github.com/NightCatSama/vue-slider-component/tree/v2), we can see there is not vue2-slider.vue file from the master branch, but current gantt-elastic is using vue2-slider.vue at https://github.com/neuronetio/gantt-elastic/blob/master/src/components/Header.vue#L117

### **Describe the solution you'd like**

- Update README file to note prerequisites of gantt-elastic, such as:
`npm install --save vue-switches`
`npm install --save vue-slider-component@2.8.16`

- Or support latest version of dependencies

**Comment by neuronetio** [comment]
Ok, will try to update this in next version of gantt

**Comment by neuronetio** [comment]
check out 0.12.8

**Comment by neuronetio** [comment]
in 0.13.0 header was moved outside gantt-elastic into gantt-elastic-header

**Comment by HavenLin** [comment]
glad to heard up. thanks a lot.
