### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by FrankQF823** [neuronetio/gantt-elastic#44]
i try to use it in my project, but it has an error.please help

**Comment by FrankQF823** [comment]
![image](https://user-images.githubusercontent.com/40521316/56116547-af2adb80-5f98-11e9-94ec-4994cebf6adb.png)

**Comment by neuronetio** [comment]
paste few tasks here and options you are using

**Comment by neuronetio** [comment]
try the latest version, it should be ok right now

**Comment by neuronetio** [comment]
I'm closing this issue but if problem still exists, feel free to reopen it
