### ISSUE TITLE
Add more zoom

### ISSUE THREAD

**Issue by lorenzocostalunga** [neuronetio/gantt-elastic#45]
Hi,
is there any way to zoom down to 10 minutes or less?

I have a task list with ranges for example from 04-24/2019 10:05:00 to 04-24/2019 10:27:00.

Great project.

**Comment by neuronetio** [comment]
I will try to add another row with minutes below hours

**Comment by neuronetio** [comment]
and of course shift minimal zoom property

**Comment by neuronetio** [comment]
I've added this issue to my todo list.
