### ISSUE TITLE
Extend documentation

### ISSUE THREAD

**Issue by mihnayan** [neuronetio/gantt-elastic#47]
Hi!

It is probably need to add a description of the task properties `parentId` and `dependentOn` in the [tasks description](https://github.com/neuronetio/gantt-elastic/wiki/Tasks) on the wiki page. These properties are used in the example but they are not mentioned in the documentation.

**Comment by neuronetio** [comment]
yap, documentation needs to be updated 👍

**Comment by neuronetio** [comment]
new major version is going to be released soon, so i will wrote documentation only to second version
