### ISSUE TITLE
This project looks really nice! Is there a roadmap?

### ISSUE THREAD

**Issue by strich** [neuronetio/gantt-elastic#48]
This looks like something I could really utilize for a project I have, and I'd be interested in contributing where I can. Is there any kind of roadmap or intended usecase for this lib yet?

**Comment by neuronetio** [comment]
Thanks!
For now I'm focused to finish some work and release stable 1.0 version.
Maybe later I will start to build some kind of project manager in my free time with gantt, kanban and other stuff, but I don't know yet, time will show.
For now, I'am working on it without concrete plan so I don't know what I will do in the next versions.
thanks again
