### ISSUE TITLE
Syntax Error: Unexpected token (592:10)

### ISSUE THREAD

**Issue by Sharvadze** [neuronetio/gantt-elastic#51]
Couldn't get complied version of GanttElastic to work. I'm using an old webpack and there is no way I can update it because of dependencies

This is my error stack:

>  error  in ./~/gantt-elastic/src/GanttElastic.vue

Syntax Error: Unexpected token (592:10)

  590 |       for (let [index, task] of tasks.entries()) {
  591 |         tasks[index] = {
> 592 |           ...task,
      |           ^
  593 |           id: task[options.taskMapping.id],
  594 |           start: task[options.taskMapping.start],
  595 |           label: task[options.taskMapping.label],

 @ ./~/gantt-elastic/src/GanttElastic.vue 7:2-169
 @ 

> ./~/babel-loader/lib?{"cacheDirectory":true,"presets":[["es2015",{"modules":false}]]}!./~/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/web/dashboard/project/StageFiveComponent.vue

**Comment by neuronetio** [comment]
hmmm, maybe experimenting with some babel presets will help because `es2015` may be not enough here.
Try `es2018` if you can.

**Comment by neuronetio** [comment]
http://2ality.com/2016/10/rest-spread-properties.html
