### ISSUE TITLE
columns click function,can not get "this"

### ISSUE THREAD

**Issue by david030918** [neuronetio/gantt-elastic#52]
hi,
I want to add a click event to columns,and set a dialog visable
but in click function,I got "this" is binded to event object.
```
data() {
  return {
   lastId: 16,
  }
},
....
In option->taskList->columns:
{
html: true,
events:{
click({event, data}) {
    console.log(this.lastId++)   <-  [this.lastId] is undefined
}

```

I would appreciate for any help.

**Comment by neuronetio** [comment]
Events are not binded to Events c'mon ;) but `this` inside function in option events for sure are not pointing to your containing component.
This is intended behavior - this is up to you what you bind to your events - you can also use scoped variable in your function to get your component data.
gantt-elastic does not want to know anything about parent component - it should be kind of sandboxed and self contained thing.
I don't know how you mount gantt (as standalone component? as component in other component?) so I can't really help - more code is needed to help.
I suggest to mount via `app = new Vue(....)` option, so app will contain all your data, and then inside click handler you can use `app.lastId` data property.
```javascript
let app;
const tasks ={/*...*/};
const options = {
/*...*/
click({event, data}){
    // app is assigned here for sure because no click event will be fired before vue initialisation,
    // after vue is mounted and start working, click event will be fired, and after vue is mounted app is assigned
    app.lastId++;
}
/*...*/
};
app = new Vue({
  el:'#gantt',
  template:`<gantt-elastic :tasks="tasks" :options="options"></gantt-elastic>`,
  components: {
    ganttElastic: GanttElastic
  },
  data() {
    return {
      tasks: tasks,
      options: options,
      lastId:16,
    };
  }
});
```

**Comment by neuronetio** [comment]
You can also define function before and bind it to your app (javascript is really elastic and I like it for this :) ). 
```javascript
let app; // for now let it be here and wait for assignment
function myClickHandlerBluePrint({event, data}){
  this.lastId++;
}
const myClickHandler = myClickHandlerBluePrint.bind(app);
const options = {
/* ... */
  click: myClickHandler, // WHAAAAAT :O ?
/* ... */
};
app = new Vue({  // let assign vue instance to app variable
/* ... */
data(){
  return {
    tasks,
    options,
    lastId:16,
  };
}
/* ... */
})
```
