### ISSUE TITLE
Add task button doesn't work in the demo

### ISSUE THREAD

**Issue by gorkem-cetin** [neuronetio/gantt-elastic#53]
**Describe the bug**
Add task button does nothing

**To Reproduce**
1. Go to demo
2. Click on Add Task
3. See error

**Expected behavior**
It should have added a task

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by neuronetio** [comment]
"It works on my machine" :)
Could you take screenshot of the console please?

**Comment by gorkem-cetin** [comment]
It definitely works now, not sure why it didnt previously.

**Comment by neuronetio** [comment]
Ok, it happens ¯\_(ツ)_/¯
