### ISSUE TITLE
Question about months in the time line

### ISSUE THREAD

**Issue by zygisjas** [neuronetio/gantt-elastic#54]
I have a question about months in the time line, how can I set to see for example 3 or 2 months and so on? Could not find an answer.

**Comment by neuronetio** [comment]
To see more time before first and after last task you need to move `Expand` knob in the header.
You can also set in options something like:
```javascript
/* ... */
scope:{
  before: 31, // for 31 days before first task
  after:31 // for 31 days after last task
}
/* ... */
```
