### ISSUE TITLE
Question about date format in calendar row

### ISSUE THREAD

**Issue by nedia05** [neuronetio/gantt-elastic#55]
First thanks for your project. I want to set the format of date in calendar like : "weekdays date in number". For example I want to see in calendar "Saturday 24" instead of  "24 Saturday".
How I can do that? What property in with which component i should change? Thanks in advance for your answer.
Ps: i translate my dates in French this is why i want this format instead of the one you set in default calendar

**Comment by neuronetio** [comment]
Takie a look at this configuration https://github.com/neuronetio/gantt-elastic/blob/7474fb594f05883e4651d28020d90995596d4193/src/GanttElastic.vue#L168
Just copy whole calendar property and paste it in your options.

**Comment by neuronetio** [comment]
Or better, copy just what you need.
Options are extended so you can choose what you want.
For example if you need just day format, make calendar object and inside put empty day object and copy inside only format property.

**Comment by nedia05** [comment]
I just change the format include in day object to "dddd DD" in the src/GanttElastic.vue and it works. 
Thanks for your answer

**Comment by neuronetio** [comment]
It's a bad idea to modify original source files.
Do it this way:
```javascript
new Vue({
components:{ 'gantt-elastic': GanttElastic},
data:{
  tasks:[/* your tasks here */],
  dynamicStyle:{/* your style here */},
  options:{
    /* your other options here */
    calendar: {
      hour: {
        format: {
          long(date) {
            return date.format('HH:mm');
          },
          medium(date) {
            return date.format('HH:mm');
          },
          short(date) {
            return date.format('HH');
          }
        }
      },
      day: {
        format: {
          long(date) {
            return date.format('DD dddd');
          },
          medium(date) {
            return date.format('DD ddd');
          },
          short(date) {
            return date.format('DD');
          }
        }
      },
      month: {
        format: {
          short(date) {
            return date.format('MM');
          },
          medium(date) {
            return date.format("MMM 'YY");
          },
          long(date) {
            return date.format('MMMM YYYY');
          }
        }
      }
    },
  }
}
})
```
