### ISSUE TITLE
Change the time interval bearable by the default gantt calendar

### ISSUE THREAD

**Issue by nedia05** [neuronetio/gantt-elastic#57]
Hi, I want to change the time interval bearable by the default gantt calendar. For example, when you put a start date in 2014 and an end date in 2019, the current calendar takes longer to display the data in the chart. Do you know which component is responsible of this management of the time interval displayable by the calendar? Thanks

**Comment by neuronetio** [comment]
You can divide your tasks into years or quarters and then add some select box to filter it.
Another solution is to listen scroll event and prepend / append some tasks when scroll pos is in certain time.

**Comment by neuronetio** [comment]
You can also load all tasks with property `collapsed` set to `true`.
