### ISSUE TITLE
Computed property was assigned but it has no setter

### ISSUE THREAD

**Issue by AlexanderYW** [neuronetio/gantt-elastic#6]
**Describe the bug**
When the vue component is initialized the logs the following errors
`Computed property "horizontalLines" was assigned to but it has no setter.`
`Computed property "verticalLines" was assigned to but it has no setter.`

**To Reproduce**
1. Add the gantt-elastic to your SPA project
2. View the page the component is displayed on

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4184558/50160971-cbfd1e00-02da-11e9-8935-654bfb1aac5d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox, Edge, Chrome
 - Version FF

**Smartphone (please complete the following information):**
 - Version Firefox 63.0.3, Chrome 71.0.3578.98, Edge 42.17134.1.0

**Additional context**
The project is a single page application

Built using webpack 3.12.x

Vue 2.5.19
Vue-router 3.0.2
dayjs 1.7.8
gantt-elastic 5.0.4

**Comment by neuronetio** [comment]
It's weird, computed property might be just functions. Problem is probably elsewhere.
Are you trying to add some content inside gantt? 
like `<gantt-elastic><your-component></your-component></gantt-elastic>` ?
Try to remove content inside, if this not work paste your template here.

**Comment by neuronetio** [comment]
When searchin on [google](https://www.google.com/search?q=Computed%20property%20was%20assigned%20to%20but%20it%20has%20no%20setter) most of those problems are caused by vuex.
Do you use vuex?

**Comment by neuronetio** [comment]
Ok, in developer mode I have the same issue.

**Comment by neuronetio** [comment]
the problem was in return statement of those two functions `verticalLines` and `horizontalLines` inside `Grid.vue` that should return only `lines` variable (without assigning)

https://github.com/neuronetio/gantt-elastic/blob/master/src/components/Chart/Grid.vue#L97
https://github.com/neuronetio/gantt-elastic/blob/master/src/components/Chart/Grid.vue#L112

for quick fix you can edit those lines and return only `lines` without assigment
I will fix this later

**Comment by AlexanderYW** [comment]
Hi neuronetio,

Sorry for the "late" response, and i see you found the issue :)

Just to clear your questions up, no I dont have any content inside the element, neither do i use vuex

As it is now i'm using the NPM package, with a CI build flow when deploying, so i might just wait for you to release a bug fix for this one, thanks any way!

**Comment by neuronetio** [comment]
New version is available without this bug 🐛 
also Header component was moved outside gantt so you can use your own UI library.
If you want standard header you can `import Header from 'gantt-elastic/src/components/Header.vue'`
and then use `header` slot - take a look at examples folder.

**Comment by neuronetio** [comment]
Leave a ⭐️ thanks!
