### ISSUE TITLE
Question about gantt customization

### ISSUE THREAD

**Issue by mits87** [neuronetio/gantt-elastic#60]
Hi,

First of all I would like to thank you for really great library!
I'm trying to customize a little the plugin and I have a few related questions:

1. How can I round the round the polygon `task` corners like here: https://www.dropbox.com/s/33oyz3lk999yu7j/Screenshot%202019-06-09%2019.24.44.png?dl=0

2. Related to the previous point - how can I put some different text than `label` to inside the polygon (not next to as is already)? 

3. How can I disabled all default styles? I would like to put my own without `important` keyword. 

4. How can I disabled / remove resizer and top expander element: 
https://www.dropbox.com/s/a5d8edlq90ir19j/Screenshot_2019-06-09_19_28_02.png?dl=0

5. How can I put HTML text to calendar rows?
https://www.dropbox.com/s/tbqexswk4mkw0n8/Screenshot_2019-06-09_19_28_03.png?dl=0

6. When I don't have any tasks then my calendar disappear- I would like to see always calendar from specific date to specific date- let's say from 1980-01-01 to 2024-01-01 ?

7.  How can I put different background for "parent" row?
https://www.dropbox.com/s/oniw59t6wobsh9d/Screenshot_2019-06-09_19_28_04.png?dl=0 

8. How can I put some value/text inside every cell?
https://www.dropbox.com/s/yxy4pd2a2l3ndl6/Screenshot%202019-06-09%2022.37.10.png?dl=0

Thank you in advance for answer.

**Comment by neuronetio** [comment]
1. The only way for now it is to create copy of `components/Chart/Row/Task.vue` and modify it (especially svg code). Build it with some bundler you prefer. Then before initialization replace this component in loaded `window.GanttElastic` structure (`GanttElastic.components.....components...components`).
2. Same as before you can modify `Task.vue`.
3. For now it is not possible, but PRO version will have it.
4. You can remove `expander` property from column. 
If you want remove resizer you can add `display:none` in `dynamicStyle` option:
```javascript
dynamicStyle: {
  'task-list-header-resizer-wrapper': {
    display: 'none'
  }
},
```
5. You cannot - only when you replace subcomponents by yourself like in point 1. PRO version will have option for this.
6. PRO version will have it.
7. You cannot without replacing subcomponents. PRO version will have it.
8. PRO version will have posibility to create custom rows which can contain custom content basing on the date of the cell - probably function with timestamp.

**Comment by neuronetio** [comment]
I'm closing this issue but feel free to respond here.
