### ISSUE TITLE
Too many elements lead to slow pages

### ISSUE THREAD

**Issue by qinchenguang** [neuronetio/gantt-elastic#63]
**Describe the bug**
When I use the calendar too widely. For example, in three years, 40 tasks rendered more than 10,000 results dom, resulting in page carton

**Comment by neuronetio** [comment]
I'm working on it. Maybe 2.0 release will have better performance.

**Comment by qinchenguang** [comment]
@neuronetio  2.0 When will it be released? Maybe I can help you with something.

**Comment by neuronetio** [comment]
I think that till the end of next month it might be done, but I don't like to give a word for this...
I am rewriting the whole component, so I do not know what I will do in a moment, so You can not help too much right now.
But thanks!
