### ISSUE TITLE
Not working on Internet explorer

### ISSUE THREAD

**Issue by mahmad2504** [neuronetio/gantt-elastic#65]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by neuronetio** [comment]
It's 2019 😆

**Comment by neuronetio** [comment]
If you need you can tranform it with Babel... But who is using IE nowadays?
