### ISSUE TITLE
Can I customize style?

### ISSUE THREAD

**Issue by Awake17** [neuronetio/gantt-elastic#67]
I can't find any infomation about style. It will be wonderful if I can customize it by the documentation.

**Comment by neuronetio** [comment]
you can modify style with `dynamicStyle` property

https://github.com/neuronetio/gantt-elastic/blob/master/src/style.js

**Comment by neuronetio** [comment]
https://github.com/neuronetio/gantt-elastic/blob/master/examples/vue.edit.html#L22

**Comment by Awake17** [comment]
OK, it works,thank you.

**Comment by DanielRuf** [comment]
This does not work with `main-view-container` for `gantt-elastic__main-view-container`.

The docs are very unclear and mostly missing.
