### ISSUE TITLE
How can I invoke function in 'title'?

### ISSUE THREAD

**Issue by Awake17** [neuronetio/gantt-elastic#68]
```
title: ` <a @click="this.$router.push({ path: /user/${task.id}})">${task.post.title}</a>`,
```
here I want to go to a new page with vue-router,but it doesn't work and be compiled as:

![image](https://user-images.githubusercontent.com/32544336/62420348-47bda680-b6c3-11e9-98fb-38bfec116c08.png)

I raise this because by using 'href' to redirect to a new page will clear all state in vuex.

**Comment by neuronetio** [comment]
I think you need to replace component from gantt that is responsible for this.
`GanttElastic.components... = your modified one`

**Comment by neuronetio** [comment]
You can also change route dynamically
https://github.com/neuronetio/gantt-elastic/blob/master/examples/vue.edit.html#L317
just add event and push route `route.push`

**Comment by Awake17** [comment]
I define the click function in events, but in the function scope vue-router doesn't work.

**Comment by neuronetio** [comment]
I'm guessing, maybe try to bind this function to proper vue instance after it was created like
```js
created(){
  /*...*/.events.click = /*...*/.events.click.bind(this);
}
```

**Comment by neuronetio** [comment]
and inside click function use something like `this.$router.push('...')`
