### ISSUE TITLE
Dependency lines issue

### ISSUE THREAD

**Issue by Nexxxt99** [neuronetio/gantt-elastic#78]
When one task has a dependency on several tasks that end at the same time, their dependenсylines may not display correctly:
![image](https://user-images.githubusercontent.com/18030536/65877743-1268c880-e395-11e9-88dd-ed49628bfd4b.png)
The horizontal line is between the main and the dependent task in the middle(red line) and in some cases can cross the task (blue line):
![image](https://user-images.githubusercontent.com/18030536/65878221-2cef7180-e396-11e9-9ce9-db9e7e17ad0c.png)

Is it possible to change the calculation for dependencyline so that the horizontal line is directly above the task?
![image](https://user-images.githubusercontent.com/18030536/65879480-8ce71780-e398-11e9-9077-5884bdc0a8a2.png)

**Comment by neuronetio** [comment]
dependency lines will be rewritten in the upcoming version, which may be released until the next month
