### ISSUE TITLE
Unknown custom element: <foreignObject> into TaskList.vue

### ISSUE THREAD

**Issue by renaudham** [neuronetio/gantt-elastic#8]
**Describe the bug**
When I add a ganttchart into my page, in a vuejs page component in a SPA,
I have this issue, as described in the Console:

>  " [Vue warn]: Unknown custom element: <foreignObject> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
> 
> found in
> 
> ---> &lt;TaskList&gt; at node_modules\gantt-elastic\src\components\TaskList\TaskList.vue
>        &lt;MainView&gt; at node_modules\gantt-elastic\src\components\MainView.vue
>          &lt;GanttElastic&gt; at node_modules\gantt-elastic\src\GanttElastic.vue "

result: the task list on left appears ok, but the charts on right are not visible, all is empty

**To Reproduce**
1. Add the &lt;gantt-elastic :tasks="gantttasks" :options="ganttoptions" &gt; &lt;/gantt-elastic&gt;  into a page, into a tab in my case

See screenshots result
![image](https://user-images.githubusercontent.com/5046926/50565379-94f12880-0d2e-11e9-8403-1deccda733b3.png)

**Comment by neuronetio** [comment]
That is weird [take a look](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject)
Maybe upgrading your vue version will help

**Comment by neuronetio** [comment]
I don't have this problem.
Again, I think that this is vue related bug - [look at this vue bug report](https://github.com/vuejs/vue/issues/4813) - you have the same problem here (I think).
If you update your vue to latest version and problem will still exists, I will reopen this issue.
Thanks for report anyway!

**Comment by neuronetio** [comment]
Take a look at this [fiddle](https://jsfiddle.net/daswu3ft/) 
Remove vue version `2.3.0` and uncomment version `2.5.17` instead - problem does not exists anymore.

**Comment by renaudham** [comment]
Hi

Still not working with last updates.

Updated all to latest version, same issue.

Note that I use it via WebPack and Npm, not loading the script in a tag in the page
and its a subcomponent of a page with many other elements.

But your link is right, the problem seems to be ForeignObject as first item in component.

The point is that when I look your source, in TaskList.vue from your code,
its ForeignObject as first item
`**<template>
  <foreignObject**
    class="gantt-elastic__task-list-wrapper"
    ref="taskListWrapper"
    :style="root.style('task-list-wrapper')"
    x="0"`


that seems to be exactly the case and that's what is rejected both by my firefox and Chrome latest versions.

The strange thing is more why its working for you and some other peoples
https://github.com/vuejs/vue/issues/4813

so I guess this should probably be updated by you first into  TaskList.vue ,
should you?
Because I guess this will happend for many peoples as soon as they don't use this gantt chart component as a sub part of a page and not as unique component in a page..

The warning in my browser specifically target this taskList.vue element.

Hoping you can find it, thanks for the great job anyway.

Regards

**Comment by renaudham** [comment]
Sorry, me again.

Maybe that the issue with ForeginObject is ok now, I don't see the same alert anymore, but maybe its a second and different thing

I will open a new ticket for this
