### ISSUE TITLE
 'options-locale' does not take effect

### ISSUE THREAD

**Issue by yifire** [neuronetio/gantt-elastic#80]
I am having a problem during use, the options-locale is set but it does not take effect.
This is my code：
`<gantt-elastic :options="options" :tasks="tasks">
      <gantt-header slot="header"></gantt-header>
    </gantt-elastic>`
`locale: {
          code: "zh-cn",
          Now: "今天",
          "X-Scale": "列宽",
          "Y-Scale": "行高",
          "Task list width": "标题宽度",
          "Before/After": "调整时间范围",
          "Display task list": "是否显示项目名称"
        }`
result：
![image](https://user-images.githubusercontent.com/27733379/66694311-abc4a280-ece4-11e9-90e5-a8f45214a942.png)

OS: windows 10 1903
Browser: chrome  77.0.3865.90
Version: 1.0.10
Vue：2.6.10

**Comment by vasilek** [comment]
Hi! You need to add props 'options' to gantt-header. It's look like this:
`<gantt-elastic :options="options" :tasks="tasks"> <gantt-header slot="header" :options="options"></gantt-header> </gantt-elastic>`

**Comment by neuronetio** [comment]
if the problem still occurs - respond here and I will reopen this issue
