### ISSUE TITLE
"Unexpected value NaN% parsing width attribute" warning when adding task to chart

### ISSUE THREAD

**Issue by rawallerstein** [neuronetio/gantt-elastic#84]
**Description**
When adding a task to the chart the browser console shows two warnings.
"Unexpected value NaN% parsing width attribute."
"Unexpected value undefined% parsing x attribute."

**To Reproduce**
1. Have Gantt Chart being displayed
2. Have tasks come from computed property (using start and end instead of start and duration)
3. Make a change that triggers a re-compute of the computed property
4. Check the browser console for warnings

**Expected behavior**
I didn't expect to get these warnings. I suspected it might be for tasks with an empty duration as the warnings seems to come from the drawing of the duration polygons. But all tasks are giving this warning.

**Desktop**
 - OS: Ubuntu 18.0.4
 - Browser: Firefox, Chrome
 - Version: 69.0.2(64bit), 77.0.3865.90(64-bit)

**Comment by zhangchengkk** [comment]
tasks[index].percent is required. : )

**Comment by neuronetio** [comment]
show your config

**Comment by neuronetio** [comment]
> Have tasks come from computed property (using start and end instead of start and duration)

maybe try to set duration as: `end-start` ?

**Comment by rawallerstein** [comment]
Zhangchengkk got it in one. Fantastic!
