### ISSUE TITLE
gantt-schedule-timeline-calendar Transition Schedule

### ISSUE THREAD

**Issue by andreMariano90** [neuronetio/gantt-elastic#85]
I know its a little recent (3 days) but I saw the README saying this project is being moved to gantt-schedule-timeline-calendar, I was about to use this project starting now, but I will wait then. 

Is there a date or a schedule that you plan on releasing samples and other stuff in the gantt-schedule-timeline-calendar? Is just so I can plan when to revisit the other project

**Comment by neuronetio** [comment]
I will **try** to release new project at the end of the next month, but I don't give word for it.
