### ISSUE TITLE
blocks browser when no tasks given (empty array)

### ISSUE THREAD

**Issue by DanielRuf** [neuronetio/gantt-elastic#86]
**Describe the bug**
When we provide an empty array for the tasks the browser is loading forever but does not respond / hangs.

**To Reproduce**

**Expected behavior**
It should not hang when an empty tasks array is used.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
VueJS

**Comment by DanielRuf** [comment]
Following is thrown then:

![image](https://user-images.githubusercontent.com/827205/68407385-c410cb80-0183-11ea-8853-359a8d8924db.png)

**Comment by skanehira** [comment]
@DanielRuf @neuronetio 
I have same problem...
Is there a solution or alternative?

**Comment by rulai-ymwang** [comment]
I figured this out.  Check the code below.

https://github.com/neuronetio/gantt-elastic/blob/e93210e5b13711194407b43748a7a3873d631f49/src/GanttElastic.vue#L1326-L1352


If no tasks given, the firstTaskTime will be  Number.MAX_SAFE_INTEGER and the lastTaskTime will be 0. They are both invalid time ms.  

We can set reasonable values to them when no tasks given.  Fix could like below (set the default time range from today to 7 days later ):

```
let firstTaskTime = Number.MAX_SAFE_INTEGER;
      let lastTaskTime = 0;
      if (this.state.tasks.length === 0 ) {
        firstTaskTime = dayjs().hour(0).minute(0).second(0).toDate().getTime();
        lastTaskTime = dayjs().hour(0).minute(0).second(0).add(7, 'day').toDate().getTime();
      } else {
        for (let index = 0, len = this.state.tasks.length; index < len; index++) {
          let task = this.state.tasks[index];
          if (task.startTime < firstTaskTime) {
            firstTaskTime = task.startTime;
          }
          if (task.startTime + task.duration > lastTaskTime) {
            lastTaskTime = task.startTime + task.duration;
          }
        }
      }
```

@neuronetio I  will give a PR later.  Could you please help reviewing it? Thanks!

**Comment by rulai-ymwang** [comment]
Here is the pr: #101

**Comment by monroenikko** [comment]
> I figured this out. Check the code below.
> 
> https://github.com/neuronetio/gantt-elastic/blob/e93210e5b13711194407b43748a7a3873d631f49/src/GanttElastic.vue#L1326-L1352
> 
> If no tasks given, the firstTaskTime will be Number.MAX_SAFE_INTEGER and the lastTaskTime will be 0. They are both invalid time ms.
> 
> We can set reasonable values to them when no tasks given. Fix could like below (set the default time range from today to 7 days later ):
> 
> ```
> let firstTaskTime = Number.MAX_SAFE_INTEGER;
>       let lastTaskTime = 0;
>       if (this.state.tasks.length === 0 ) {
>         firstTaskTime = dayjs().hour(0).minute(0).second(0).toDate().getTime();
>         lastTaskTime = dayjs().hour(0).minute(0).second(0).add(7, 'day').toDate().getTime();
>       } else {
>         for (let index = 0, len = this.state.tasks.length; index < len; index++) {
>           let task = this.state.tasks[index];
>           if (task.startTime < firstTaskTime) {
>             firstTaskTime = task.startTime;
>           }
>           if (task.startTime + task.duration > lastTaskTime) {
>             lastTaskTime = task.startTime + task.duration;
>           }
>         }
>       }
> ```
> 
> @neuronetio I will give a PR later. Could you please help reviewing it? Thanks!

My gantt is working now. Nice! thanks
