### ISSUE TITLE
will this still be maintained?

### ISSUE THREAD

**Issue by DanielRuf** [neuronetio/gantt-elastic#87]
There are many who use this library. It would be not so great if this project would not be further maintained.

**Comment by neuronetio** [comment]
gantt-schedule-timeline-calendar is just like next major release (v2) of gantt-elastic but with different name
gantt-elastic cannot be maintained because of bad decisions in the core structure - there is a lot troubles with performance and when it comes to adding new features

**Comment by neuronetio** [comment]
of course some minor bugs of gantt-elastic will be fixed but with slower response time right now
