### ISSUE TITLE
style for calendar-wrapper not applied (width)

### ISSUE THREAD

**Issue by DanielRuf** [neuronetio/gantt-elastic#88]
When we try to set the `width` for `calendar-wrapper` it does not work. It seems to be set / overwritten dynamically.

**Comment by DanielRuf** [comment]
I guess this is because of `...root.style['calendar-wrapper'], width: root.state.options.width + 'px'` where the last value overwrite the previous values.

We need the header for the full available width.

**Comment by DanielRuf** [comment]
It should be probably `width: root.state.options.width, ...root.style['calendar-wrapper']`

`px` values do not always make sense.

**Comment by neuronetio** [comment]
Event if u set the width to 100% it will not work becase each day in calendar has calculated width. With gantt-schedule-timeline-calendar you can do this but not with gantt-elastic.

**Comment by DanielRuf** [comment]
> Event if u set the width to 100% it will not work becase each day in calendar has calculated width. With gantt-schedule-timeline-calendar you can do this but not with gantt-elastic.

Seems so. This is very unfortunate =(

**Comment by neuronetio** [comment]
If you want to wait something about 1 month you can buy gantt-schedule-timeline-calendar commercial license (it will be cheap) and hire me to do stuff you need to do, so it will speed up things a lot.
Send me an mail if you are interested neuronet.io@gmail.com

**Comment by DanielRuf** [comment]
The docs are almost non-existant. We will not migrate to an untested and undocumented solution and I am more interested to contribute to the open source version of gantt-elastic. Because we currently are in the middle of a project and we use `patch-package` for now.

**Comment by neuronetio** [comment]
ok so i can't help you any more right now, sorry
