### ISSUE TITLE
Subtasks roll up to parent task

### ISSUE THREAD

**Issue by dasuchin** [neuronetio/gantt-elastic#89]
Is it possible to have the subtasks under a main task roll up to the parent task?
So when the main task is collapsed, it would actually show each task on the main parent task line, and then you'd have the ability to uncollapse it and display details about each sub task.

**Comment by neuronetio** [comment]
This is not possible in this version but [gantt-schedule-timeline-calendar](https://github.com/neuronetio/gantt-schedule-timeline-calendar) will have it builtin, even with task movement / resizing capabilities which is very hard to implement here (bad structure decisions).
