### ISSUE TITLE
Dayjs is not defined

### ISSUE THREAD

**Issue by ephraimlambarte** [neuronetio/gantt-elastic#90]
**Describe the bug**
When using the component i get an error in my console that says dayjs is not defined:
`app.js:206164 [Vue warn]: Error in render: "ReferenceError: dayjs is not defined"`

I already tried to install dayjs by running `npm install dayjs --save`

**To Reproduce**
1. Use gantt-elastic component in vue component

**Expected behavior**
No errors in console.

**Screenshots**

![image](https://user-images.githubusercontent.com/21136639/68917081-a35bfd80-07a3-11ea-9cd0-b91f12c33ee4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 78.0.3904.97 (Official Build) (64-bit)
 - Vue version: ^2.5.17

**Comment by neuronetio** [comment]
try to remove `node_modules` folder and then reinstall all dependencies with `npm i`

**Comment by mewcrazy** [comment]
`import dayjs from 'dayjs'` helped in my case

**Comment by neuronetio** [comment]
yes, you need to add dayjs to your imports or as script tag

https://github.com/neuronetio/gantt-elastic/blob/master/examples/from-readme.html#L8
