### ISSUE TITLE
more tasks for line

### ISSUE THREAD

**Issue by mbrandaocaio** [neuronetio/gantt-elastic#92]
Hey guys, is there any way to add more tasks fot the same line? like multiple tasks for the same user?
Thanks

**Comment by neuronetio** [comment]
in this lib there is no such feature and there are no plans for it (no new features in this verison), but take a look at next version at https://github.com/neuronetio/gantt-schedule-timeline-calendar

**Comment by mbrandaocaio** [comment]
I tried this version, and I think is what I need, but I cound't implement it in my vue project. Is there any example I can use?

**Comment by neuronetio** [comment]
maybe this will help https://github.com/neuronetio/gantt-schedule-timeline-calendar/blob/master/dist/examples/scheduler.html

**Comment by neuronetio** [comment]
if not you must be patient because new examples will show up soon

**Comment by mbrandaocaio** [comment]
thanks
