### ISSUE TITLE
Load events dynamically

### ISSUE THREAD

**Issue by mewcrazy** [neuronetio/gantt-elastic#95]
Hello,

as soon as I try to load events dynamically, either via push or replacing this.events with the actual events array, I need to load them from firebase first. I tried to load them in created and pass them, a computed property, and a custom function before export, like your getDate helper function.

But each time I get the following error messages in my console. And I can't shake them off, nor can I locate the error. (I'm referring to the svg/rect errors) But if I use the events array from your example, everything is fine.

How should I load my firebase entries into gantt-elastic?

![image](https://user-images.githubusercontent.com/6299479/71649576-4646e780-2d10-11ea-984f-fcc3965459fe.png)

And here my component:
https://pastebin.com/zjdFRLWh

**Comment by neuronetio** [comment]
As the error says you are using wrong version of vue - without template compiler.
It is not a problem of gantt-elastic itself.
You can use precompiled `*.vue` components or use vue version with template compiler.

**Comment by mewcrazy** [comment]
I fixed those two errors. As I was saying, I'm talking about the other errors. They appear as soon as I load tasks via function. 

Let me ask you a simpler question: How would you load the tasks into gantt-elastic, if you want to show tasks from a database. (like I'm doing in my getTasks() function)

**Comment by neuronetio** [comment]
`NaN` says that somewhere you have passed wrong data, probably dates.

**Comment by neuronetio** [comment]
you need to update `this.tasks` of course when your data is ready
it is not a gantt-elastic issue
